name: Submit Content
description: "Submit an article, blog post, video, or other links."
title: "📃 Title"
body:
  - type: input
    id: link
    attributes:
      label: "🔗 Link to content"
  - type: dropdown
    id: tech
    attributes:
      label: "Which is the best target audience for this content?"
      options:
        - "--Choose--"
        - .NET
        - C/C++
        - Go
        - Java
        - JavaScript/Web
        - Kotlin                        
        - PHP
        - Python
        - Ruby
        - Rust
        - AI
        - Architecture        
        - DevOps                
        - People/Career
        - Performance Tools
        - Software Development
        - Other
      default: 0
    validations:
      required: false
